### ISSUE TITLE
Breweries duplicates

### ISSUE THREAD

**Issue by boneeyah** [KendallScott/Case-Study#10]
Brew IDs: 2, 13, 59, 63, 96, 139, 164, 167, 262, 276, 372, 378, 383, 415, 457, 504.

These are not fully duplicated but are more of mistakes in the data, Breweries are actually duplicated, but with mistakes in the data, like same brewery, same city, but different state (typo MA instead of MI) and/or different brew_Id

**Comment by KendallScott** [comment]
For question 1-- I think it would use just the brewery dataset-- not the one that joins to beers. The part with numerous brewid-- is breweries with different beers. Brew_id is for the brewery location, so it should have duplicates.. Beer id should be unique

**Comment by boneeyah** [comment]
I don't think I explained it clearly, but I do think it's something that maybe should be addressed at least for one in particular that is kind of like a typo.
So for example Brew_ID 13 and Brew_ID 96 both correspond to a brewery named Blackrocks Brewery (same name) but are located in Marquette, MI and Marquette, MA respectively (except there is no city named Marquette in MA only in MI)

**Comment by KendallScott** [comment]
I think there might be an issue with the join for county data, cause I looked and relooked.. and there are no duplicates. I used this code to check and group: check_bb<-beer_brewery %>% group_by(State, City, Brewery) %>% dplyr::summarize(count=n()) 
check_bb_dup<-duplicated(check_bb)

**Comment by KendallScott** [comment]
I pulled a check on dups using this code:

check_bb<-beer_brewery %>% group_by(State, City, Brewery) %>% dplyr::summarize(count=n()) 
check_bb$dup<-(duplicated(check_bb$Brewery))
dups=check_bb %>% filter(dup == TRUE)
check_bb_dups = merge(x=brewery,y=dups,by="Brewery")
